//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StorageMonster.Web.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TimeZonesResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TimeZonesResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StorageMonster.Web.Properties.TimeZonesResources", typeof(TimeZonesResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT) Western Europe Time, London, Lisbon, Casablanca.
        /// </summary>
        public static string tz_0 {
            get {
                return ResourceManager.GetString("tz_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT -1:00 hour) Azores, Cape Verde Islands.
        /// </summary>
        public static string tz_m_1 {
            get {
                return ResourceManager.GetString("tz_m_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT -10:00) Hawaii.
        /// </summary>
        public static string tz_m_10 {
            get {
                return ResourceManager.GetString("tz_m_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT -11:00) Midway Island, Samoa.
        /// </summary>
        public static string tz_m_11 {
            get {
                return ResourceManager.GetString("tz_m_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT -12:00) Eniwetok, Kwajalein.
        /// </summary>
        public static string tz_m_12 {
            get {
                return ResourceManager.GetString("tz_m_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT -2:00) Mid-Atlantic.
        /// </summary>
        public static string tz_m_2 {
            get {
                return ResourceManager.GetString("tz_m_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT -3:00) Brazil, Buenos Aires, Georgetown.
        /// </summary>
        public static string tz_m_3 {
            get {
                return ResourceManager.GetString("tz_m_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT -3:30) Newfoundland.
        /// </summary>
        public static string tz_m_3_30 {
            get {
                return ResourceManager.GetString("tz_m_3_30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT -4:00) Atlantic Time (Canada), Caracas, La Paz.
        /// </summary>
        public static string tz_m_4 {
            get {
                return ResourceManager.GetString("tz_m_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT -5:00) Eastern Time (US &amp; Canada), Bogota, Lima.
        /// </summary>
        public static string tz_m_5 {
            get {
                return ResourceManager.GetString("tz_m_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT -6:00) Central Time (US &amp; Canada), Mexico City.
        /// </summary>
        public static string tz_m_6 {
            get {
                return ResourceManager.GetString("tz_m_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT -7:00) Mountain Time (US &amp; Canada).
        /// </summary>
        public static string tz_m_7 {
            get {
                return ResourceManager.GetString("tz_m_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT -8:00) Pacific Time (US &amp; Canada).
        /// </summary>
        public static string tz_m_8 {
            get {
                return ResourceManager.GetString("tz_m_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT -9:00) Alaska.
        /// </summary>
        public static string tz_m_9 {
            get {
                return ResourceManager.GetString("tz_m_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT +1:00) Brussels, Copenhagen, Madrid, Paris.
        /// </summary>
        public static string tz_p_1 {
            get {
                return ResourceManager.GetString("tz_p_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT +10:00) Eastern Australia, Guam, Vladivostok.
        /// </summary>
        public static string tz_p_10 {
            get {
                return ResourceManager.GetString("tz_p_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT +11:00) Magadan, Solomon Islands, New Caledonia.
        /// </summary>
        public static string tz_p_11 {
            get {
                return ResourceManager.GetString("tz_p_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT +12:00) Auckland, Wellington, Fiji, Kamchatka.
        /// </summary>
        public static string tz_p_12 {
            get {
                return ResourceManager.GetString("tz_p_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT +2:00) Kaliningrad, South Africa.
        /// </summary>
        public static string tz_p_2 {
            get {
                return ResourceManager.GetString("tz_p_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT +3:00) Baghdad, Riyadh, Moscow, St. Petersburg.
        /// </summary>
        public static string tz_p_3 {
            get {
                return ResourceManager.GetString("tz_p_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT +3:30) Tehran.
        /// </summary>
        public static string tz_p_3_30 {
            get {
                return ResourceManager.GetString("tz_p_3_30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT +4:00) Abu Dhabi, Muscat, Baku, Tbilisi.
        /// </summary>
        public static string tz_p_4 {
            get {
                return ResourceManager.GetString("tz_p_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT +4:30) Kabul.
        /// </summary>
        public static string tz_p_4_30 {
            get {
                return ResourceManager.GetString("tz_p_4_30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT +5:00) Ekaterinburg, Islamabad, Karachi, Tashkent.
        /// </summary>
        public static string tz_p_5 {
            get {
                return ResourceManager.GetString("tz_p_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT +5:30) Bombay, Calcutta, Madras, New Delhi.
        /// </summary>
        public static string tz_p_5_30 {
            get {
                return ResourceManager.GetString("tz_p_5_30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT +5:45) Kathmandu.
        /// </summary>
        public static string tz_p_5_45 {
            get {
                return ResourceManager.GetString("tz_p_5_45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT +6:00) Almaty, Dhaka, Colombo.
        /// </summary>
        public static string tz_p_6 {
            get {
                return ResourceManager.GetString("tz_p_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT +7:00) Bangkok, Hanoi, Jakarta.
        /// </summary>
        public static string tz_p_7 {
            get {
                return ResourceManager.GetString("tz_p_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT +8:00) Beijing, Perth, Singapore, Hong Kong.
        /// </summary>
        public static string tz_p_8 {
            get {
                return ResourceManager.GetString("tz_p_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT +9:00) Tokyo, Seoul, Osaka, Sapporo, Yakutsk.
        /// </summary>
        public static string tz_p_9 {
            get {
                return ResourceManager.GetString("tz_p_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT +9:30) Adelaide, Darwin.
        /// </summary>
        public static string tz_p_9_30 {
            get {
                return ResourceManager.GetString("tz_p_9_30", resourceCulture);
            }
        }
    }
}
