//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StorageMonster.Web.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StorageMonster.Web.Properties.ValidationResources", typeof(ValidationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account already exists.
        /// </summary>
        public static string AccountExistsError {
            get {
                return ResourceManager.GetString("AccountExistsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid account.
        /// </summary>
        public static string AccountInvalidError {
            get {
                return ResourceManager.GetString("AccountInvalidError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account not found.
        /// </summary>
        public static string AccountNotFound {
            get {
                return ResourceManager.GetString("AccountNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account was already updated.
        /// </summary>
        public static string AccountStalled {
            get {
                return ResourceManager.GetString("AccountStalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access denied.
        /// </summary>
        public static string AjaxAccessDenied {
            get {
                return ResourceManager.GetString("AjaxAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request is not acceptable.
        /// </summary>
        public static string AjaxNotAcceptable {
            get {
                return ResourceManager.GetString("AjaxNotAcceptable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request can not be processed (404).
        /// </summary>
        public static string AjaxNotFound {
            get {
                return ResourceManager.GetString("AjaxNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server error.
        /// </summary>
        public static string AjaxServerError {
            get {
                return ResourceManager.GetString("AjaxServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad request.
        /// </summary>
        public static string AntiforgeryMismath {
            get {
                return ResourceManager.GetString("AntiforgeryMismath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request is not accepatble.
        /// </summary>
        public static string BadRequestError {
            get {
                return ResourceManager.GetString("BadRequestError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified email was not found.
        /// </summary>
        public static string EmailNotFoundError {
            get {
                return ResourceManager.GetString("EmailNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &apos;{0}&apos; is invalid..
        /// </summary>
        public static string InvalidFieldFormat {
            get {
                return ResourceManager.GetString("InvalidFieldFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File location is invalid.
        /// </summary>
        public static string InvalidFileLocation {
            get {
                return ResourceManager.GetString("InvalidFileLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no permissions to view this page.
        /// </summary>
        public static string NoPermissionsError {
            get {
                return ResourceManager.GetString("NoPermissionsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no permissions to download file.
        /// </summary>
        public static string NoPermissionsToDownload {
            get {
                return ResourceManager.GetString("NoPermissionsToDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password is incorrect.
        /// </summary>
        public static string OldPasswordsMismatchError {
            get {
                return ResourceManager.GetString("OldPasswordsMismatchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &apos;{0}&apos; is required to be a minimum of {1} character(s) in length..
        /// </summary>
        public static string PasswordMinLengthFormat {
            get {
                return ResourceManager.GetString("PasswordMinLengthFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paswords must match..
        /// </summary>
        public static string PasswordsMustMatch {
            get {
                return ResourceManager.GetString("PasswordsMustMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified e-mail address already exists. Please enter a different e-mail address..
        /// </summary>
        public static string RegDuplicateEmail {
            get {
                return ResourceManager.GetString("RegDuplicateEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username already exists. Please enter a different user name..
        /// </summary>
        public static string RegDuplicateUserName {
            get {
                return ResourceManager.GetString("RegDuplicateUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password retrieval answer provided is invalid. Please check the value and try again..
        /// </summary>
        public static string RegInvalidAnswer {
            get {
                return ResourceManager.GetString("RegInvalidAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The e-mail address provided is invalid. Please check the value and try again..
        /// </summary>
        public static string RegInvalidEmail {
            get {
                return ResourceManager.GetString("RegInvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password provided is invalid. Please enter a valid password value..
        /// </summary>
        public static string RegInvalidPassword {
            get {
                return ResourceManager.GetString("RegInvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password retrieval question provided is invalid. Please check the value and try again..
        /// </summary>
        public static string RegInvalidQuestion {
            get {
                return ResourceManager.GetString("RegInvalidQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user name provided is invalid. Please check the value and try again..
        /// </summary>
        public static string RegInvalidUserName {
            get {
                return ResourceManager.GetString("RegInvalidUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The authentication provider returned an error. Please verify your entry and try again. If the problem persists, please contact your system administrator..
        /// </summary>
        public static string RegProviderError {
            get {
                return ResourceManager.GetString("RegProviderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error occurred. Please verify your entry and try again. If the problem persists, please contact your system administrator..
        /// </summary>
        public static string RegUnknownError {
            get {
                return ResourceManager.GetString("RegUnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user creation request has been canceled. Please verify your entry and try again. If the problem persists, please contact your system administrator..
        /// </summary>
        public static string RegUserRejected {
            get {
                return ResourceManager.GetString("RegUserRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &apos;{0}&apos; is required..
        /// </summary>
        public static string RequiredFieldFormat {
            get {
                return ResourceManager.GetString("RequiredFieldFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server error.
        /// </summary>
        public static string ResetInstructionSendingFailedError {
            get {
                return ResourceManager.GetString("ResetInstructionSendingFailedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad request.
        /// </summary>
        public static string StampRequired {
            get {
                return ResourceManager.GetString("StampRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage account not found.
        /// </summary>
        public static string StorageAccountNotFoundError {
            get {
                return ResourceManager.GetString("StorageAccountNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account was already updated by someone else.
        /// </summary>
        public static string StorageAccountStalled {
            get {
                return ResourceManager.GetString("StorageAccountStalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage type not found.
        /// </summary>
        public static string StoragePluginNotFoundError {
            get {
                return ResourceManager.GetString("StoragePluginNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &apos;{0}&apos; must be less than {1} characters.
        /// </summary>
        public static string StringLengthFormat {
            get {
                return ResourceManager.GetString("StringLengthFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username or password provided is incorrect..
        /// </summary>
        public static string UserNameOrPasswordIncorrect {
            get {
                return ResourceManager.GetString("UserNameOrPasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found.
        /// </summary>
        public static string UserNotFoundError {
            get {
                return ResourceManager.GetString("UserNotFoundError", resourceCulture);
            }
        }
    }
}
